apiVersion: v1
kind: Service
metadata:
  name: webhook-operator-webhook-service
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: webhook-operator