apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-operator-validating-webhook-cfg
  labels:
    app.kubernetes.io/name: webhook-operator
webhooks:
- admissionReviewVersions:
    - v1
    - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: webhook-operator-webhook-service
      namespace: default
      path: /validate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validating-webhook.webhook.zvlb.github.io
  objectSelector: {}
  rules:
    - apiGroups:
        - 'webhook.zvlb.github.io'
      apiVersions:
        - '*'
      operations:
        - CREATE
        - UPDATE
      resources:
        - '*'
      scope: '*'
  sideEffects: None
  timeoutSeconds: 30