---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webhook.zvlb.github.io
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webhook.zvlb.github.io
  resources:
  - tests/finalizers
  verbs:
  - update
- apiGroups:
  - webhook.zvlb.github.io
  resources:
  - tests/status
  verbs:
  - get
  - patch
  - update
